# Generated by Django 5.1 on 2024-09-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroPoliesportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('cep', models.CharField(max_length=11, unique=True)),
                ('numero', models.IntegerField()),
                ('quantidade_quadras', models.IntegerField()),
                ('contato_dono', models.CharField(max_length=11)),
                ('descricao', models.CharField(max_length=299)),
                ('avaliacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=20)),
                ('capacidade_minima', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(max_length=10)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('ct_pol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_poliesportivo.centropoliesportivo')),
            ],
        ),
        migrations.CreateModel(
            name='HorariosDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeira_meia_hora', models.FloatField()),
                ('segunda_meia_hora', models.FloatField()),
                ('is_ocupado', models.BooleanField()),
                ('periodo_funcionamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.periodofuncionamento')),
            ],
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('ct_pol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.centropoliesportivo')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.modalidade')),
            ],
        ),
    ]
