# Generated by Django 5.1 on 2024-11-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CidadeEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CentroPoliesportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('rua', models.CharField(max_length=70)),
                ('quantidade_quadras', models.IntegerField()),
                ('contato_dono', models.CharField(max_length=11)),
                ('descricao', models.CharField(max_length=299)),
                ('avaliacao', models.FloatField()),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.cidadeestado')),
            ],
        ),
        migrations.CreateModel(
            name='AuxPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_minima', models.IntegerField()),
                ('valor_final', models.FloatField()),
                ('ct_pol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_poliesportivo.centropoliesportivo')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(max_length=10)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('ct_pol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_poliesportivo.centropoliesportivo')),
            ],
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_pol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_poliesportivo.centropoliesportivo')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.modalidade')),
            ],
        ),
    ]
