# Generated by Django 5.1 on 2024-09-12 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_poliesportivo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidade',
            name='capacidade_minima',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='status',
        ),
        migrations.AlterField(
            model_name='centropoliesportivo',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='AuxPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_minima', models.IntegerField()),
                ('valor_final', models.FloatField()),
                ('ct_pol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.centropoliesportivo')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.modalidade')),
            ],
        ),
        migrations.DeleteModel(
            name='HorariosDisponiveis',
        ),
    ]
