# Generated by Django 5.1 on 2024-11-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro_poliesportivo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider_partida', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_termino', models.TimeField()),
                ('centro_poliesportivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.centropoliesportivo')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.modalidade')),
                ('valor_final', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.auxpartida')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento_partida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='partida.agendamentopartida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
        ),
    ]
