# Generated by Django 5.1 on 2024-11-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentopartida',
            name='valor_final',
            field=models.FloatField(),
        ),
    ]
