# Generated by Django 5.1 on 2024-11-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='partidas_concluidas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
