# Generated by Django 5.1 on 2024-11-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_poliesportivo', '0001_initial'),
        ('usuario', '0003_alter_usuario_partidas_concluidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='centro_poliesportivo.cidadeestado'),
        ),
    ]
